package gui

val BACKTRACKING_ALGORITHM = "Backtracking"
val FORWARD_CHECKING_ALGORITHM = "Forward Checking"

val IN_SEQUENCE_VALUE_HEURISTIC = "In Sequence"
val RANDOM_VALUE_HEURISTIC = "Random"

val IN_SEQUENCE_VARIABLE_HEURISTIC = "In Sequence"
val THE_MOST_RESTRICTED_DOMAIN_VARIABLE_HEURISTIC = "The Most Restricted Domain"